### ISSUE TITLE
Upload a new graph file

### ISSUE THREAD

**Issue by DeepReSearcher101** [dabreegster/route_snapper#35] opened 2023-07-04 12:04 UTC
Hello!
I think that this site is very useful for my work but I have trouble with setting the area of interest, the graph file.
If I use the exported result from this tool [https://a-b-street.github.io/osm2streets/](a-b-street) - Boundary download, which is a geojson file, I'm not seeing the new area. I have to do something more?
Thanks.

**Comment by dabreegster** [comment] 2023-07-04 12:14
Hi! The input file has to be built using https://github.com/dabreegster/route_snapper/blob/main/user_guide.md#building-a-graph-file right now. I'll deduplicate this issue with #28 -- that would give you a much easier way to create that file from your browser. I can try and implement that in the next week.

Out of curiosity, can you share anything about how you're using the tool?

**Comment by dabreegster** [comment] 2023-07-04 12:14
Duplicate of #28

**Closed as completed by dabreegster** 2023-07-04 12:14 UTC

**Comment by DeepReSearcher101** [comment] 2023-07-04 12:37
> Hi! The input file has to be built using https://github.com/dabreegster/route_snapper/blob/main/user_guide.md#building-a-graph-file right now. I'll deduplicate this issue with #28 -- that would give you a much easier way to create that file from your browser. I can try and implement that in the next week.
> 
> Out of curiosity, can you share anything about how you're using the tool?

Yes, sure. I'm in law enforcement and I am in charge of creating patrol areas and analyze what's happening inside those areas. And instead of creating those areas somehow manually, this tool seems to perform much faster. I can't wait to see the result, especially for less technical guys like me :)
Thanks for the fast reply.

**Comment by dabreegster** [comment] 2023-07-06 12:42
Hi @potterthecop, give https://dabreegster.github.io/route_snapper/import.html a try. Let me know if anything breaks or the instructions aren't clear. Thanks!

**Comment by DeepReSearcher101** [comment] 2023-07-07 11:44
> Hi @potterthecop, give https://dabreegster.github.io/route_snapper/import.html a try. Let me know if anything breaks or the instructions aren't clear. Thanks!

Thanks for the update, Dustin @dabreegster . It works very good. I managed to create the graph and upload it.

One issue I had trouble with in the window where you can create the graph is when you click on the polygon tool, nothing happen. To be more intuitive, maybe, when you have time, to change the mouse pointer icon with something else similar to a selection tool?

Also, you have in plan to create an option in order to download the newly created area? in geojson format maybe or in another..That would be really useful also.

Thanks again, you are doing a great job!

**Comment by dabreegster** [comment] 2023-07-10 10:26
Hi, both changes are done! That first is particularly useful -- https://dabreegster.github.io/route_snapper/ is meant to be an example for programmers using this library in their own project, not really an end-user tool. But no reason not to make small steps in this direction.

**Comment by DeepReSearcher101** [comment] 2023-07-10 17:29
> Hi, both changes are done! That first is particularly useful -- https://dabreegster.github.io/route_snapper/ is meant to be an example for programmers using this library in their own project, not really an end-user tool. But no reason not to make small steps in this direction.

Thank you very much. A small step to you, a giant step for me :) It is working very well and for me / others like me, it's super useful.
Have a great day!
